// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9AAsANEeO6zWa0lOp-bWelKlT6W88hl0',
    appId: '1:923353787908:web:cf014d79b94852c24e4f51',
    messagingSenderId: '923353787908',
    projectId: 'ai-chat-d516e',
    authDomain: 'ai-chat-d516e.firebaseapp.com',
    storageBucket: 'ai-chat-d516e.firebasestorage.app',
    measurementId: 'G-H2DT3E9X6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBgl7EF_dof7DAhP5H29aRM2rhsuaaEVw',
    appId: '1:923353787908:android:392a83563eadad4b4e4f51',
    messagingSenderId: '923353787908',
    projectId: 'ai-chat-d516e',
    storageBucket: 'ai-chat-d516e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuwDkDH58QHT_3yJY90_ihjKZfvlvY-s',
    appId: '1:923353787908:ios:399801a0964aa9944e4f51',
    messagingSenderId: '923353787908',
    projectId: 'ai-chat-d516e',
    storageBucket: 'ai-chat-d516e.firebasestorage.app',
    iosClientId: '923353787908-oi5fe1tmshd6k0k6qgfid8733t3qu777.apps.googleusercontent.com',
    iosBundleId: 'com.example.memesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuwDkDH58QHT_3yJY90_ihjKZfvlvY-s',
    appId: '1:923353787908:ios:399801a0964aa9944e4f51',
    messagingSenderId: '923353787908',
    projectId: 'ai-chat-d516e',
    storageBucket: 'ai-chat-d516e.firebasestorage.app',
    iosClientId: '923353787908-oi5fe1tmshd6k0k6qgfid8733t3qu777.apps.googleusercontent.com',
    iosBundleId: 'com.example.memesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9AAsANEeO6zWa0lOp-bWelKlT6W88hl0',
    appId: '1:923353787908:web:7cf9b927aa3eeb2d4e4f51',
    messagingSenderId: '923353787908',
    projectId: 'ai-chat-d516e',
    authDomain: 'ai-chat-d516e.firebaseapp.com',
    storageBucket: 'ai-chat-d516e.firebasestorage.app',
    measurementId: 'G-YYWVGTP91M',
  );
}
